Models/RockApi/Entities/Referral.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RockApi
{
    public class Referral : IRockEntity
    {
        public string id { get; set; }

        [Display(Name = "Display Name")]
        public string displayName { get; set; }

        [Display(Name = "First Name")]
        public string firstName { get; set; }

        [Display(Name = "Last Name")]
        public string lastName { get; set; }

        [Display(Name = "Full Name")]
        public string fullName { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }

        [Display(Name = "External ID")]
        public string externalIdentifier { get; set; }

        [Display(Name = "Phone Number")]
        public string phoneNumber { get; set; }

        [Display(Name = "Amount")]
        public double amount { get; set; }

        [Display(Name = "Preferred Contact")]
        public string preferredContact { get; set; }

        [Display(Name = "Status")]
        public string status { get; set; }

        [Display(Name = "Company")]
        public string companyName { get; set; }

        [Display(Name = "Note")]
        public string note { get; set; }

        [Display(Name = "Public Note")]
        public string publicNote { get; set; }

        [Display(Name = "Custom Option 1 Name")]
        public string customOption1Name { get; set; }

        [Display(Name = "Custom Option 2 Name")]
        public string customOption2Name { get; set; }

        [Display(Name = "Custom Text 1 Name")]
        public string customText1Name { get; set; }

        [Display(Name = "Custom Text 2 Name")]
        public string customText2Name { get; set; }

        [Display(Name = "Custom Text 3 Name")]
        public string customText3Name { get; set; }


        [Display(Name = "Custom Option 1 Value")]
        public string customOption1Value { get; set; }

        [Display(Name = "Custom Option 2 Value")]
        public string customOption2Value { get; set; }

        [Display(Name = "Custom Text 1 Value")]
        public string customText1Value { get; set; }

        [Display(Name = "Custom Text 2 Value")]
        public string customText2Value { get; set; }

        [Display(Name = "Custom Text 3 Value")]
        public string customText3Value { get; set; }

        //Not included in view
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string amountFormatted { get; set; }
        public string source { get; set; }
        public string programId { get; set; }
        public string programName { get; set; }
        public string programTitle { get; set; }
        public string referringMemberId { get; set; }
        public string referringMemberName { get; set; }
        public string memberEmail { get; set; }
        public string memberReferralCode { get; set; }
        public string memberExternalIdentifier { get; set; }
        public string approvedDate { get; set; }
        public string qualifiedDate { get; set; }
        public string conversionNote { get; set; }
        public string conversionIPAddress { get; set; }
        public string utmSource { get; set; }
        public string utmMedium { get; set; }
        public string utmCampaign { get; set; }
        public string browserReferrerUrl { get; set; }
        public string IPAddressSource { get; set; }
    }

    public class NewReferral
    {
        [Display(Name = "Referral Code")]
        public string referralCode { get; set; }

        [Display(Name = "First Name")]
        public string firstName { get; set; }

        [Display(Name = "Last Name")]
        public string lastName { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }
    }
}

Models/RockApi/Services/Referrals/ReferralQuery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RockApi
{
    public class ReferralQuery
    {
        public ReferralPrimaryInfo primaryInfo { get; set; }
        public ReferralSecondaryInfo secondaryInfo { get; set; }
        public ReferralTertiaryInfo tertiaryInfo { get; set; }
        public ReferralFuzzyInfo fuzzyInfo { get; set; }
    }
    public class ReferralPrimaryInfo
    {
        public string referralId { get; set; }
    }
    public class ReferralSecondaryInfo
    {
        public string externalIdentifier { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
    }
    public class ReferralTertiaryInfo
    {
        public string ProgramId { get; set; }
        public string ProgramName { get; set; }
        public string ProgramTitle { get; set; }
    }
    public class ReferralFuzzyInfo
    {
        public string Identifier { get; set; }
    }
}

Models/RockApi/Services/Referrals/ReferralService.cs
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RockApi.Models;

namespace RockApi.Services
{
    public class ReferralService : Service<Referral>
    {
        protected override string ListPath => "api/referrals";
        protected override string GetSinglePath => "api/referral/getsingle";
        protected override string CreatePath => "api/referrals";
        protected override string UpdatePath => "api/referral/update";
        protected override string RemovePath => "api/referral/remove";

        /// <summary>
        ///  List
        /// </summary>
        /// <param name="QueryOptions">A collection of query string parameters</param>
        /// <returns>A collection of members</returns>
        public async Task<List<Referral>> ListAsync(QueryOptions QueryOptions = null)
        {
            var ReferralSet = await this.ListEntitiesAsync<ReferralSet>(QueryOptions);
            return ReferralSet.referrals.ToList();
        }

        /// <summary>
        ///  Get
        /// </summary>
        /// <param name="QueryOptions">A collection of query string parameters</param>
        /// <returns>A single member</returns>
        public Task<Referral> GetAsync(QueryOptions QueryOptions = null)
        {
            return this.GetEntityAsync(QueryOptions);
        }

        /// <summary>
        /// Create
        /// </summary>
        /// <param name="NewReferral">A referral to create</param>
        /// <returns></returns>
        public async Task CreateAsync(NewReferral NewReferral)
        {
            await this.CreateEntityAsync(NewReferral);
        }

        /// <summary>
        /// Update
        /// </summary>
        /// <param name="UpdateReferralInfos">An update object that contains a query object to identify the referral to update and a referral object with the new values</param>
        /// <returns></returns>
        public async Task UpdateAsync(List<UpdateReferralInfo> UpdateReferralInfos)
        {
            await this.UpdateEntityAsync(UpdateReferralInfos);
        }

        /// <summary>
        /// Delete
        /// </summary>
        /// <param name="UpdateReferralInfos">An delete object that contains a query object to identify the referral to delete</param>
        /// <returns></returns>
        public async Task RemoveAsync(List<RemoveReferralInfo> RemoveReferralInfos)
        {
            await this.RemoveEntityAsync(RemoveReferralInfos);
        }
    }
}

Models/RockApi/Services/Referrals/RemoveReferralInfo.cs
namespace RockApi
{
    public class RemoveReferralInfo
    {
        public RemoveReferralInfo() { }

        //Default constructor to simplify searching by only referralid
        public RemoveReferralInfo(string referralid)
        {
            query = new ReferralQuery()
            {
                primaryInfo = new ReferralPrimaryInfo()
                {
                    referralId = referralid,
                }
            };
        }
        public ReferralQuery query { get; set; }
    }
}

Models/RockApi/Services/Referrals/UpdateReferalInfo.cs
namespace RockApi
{
    /// <summary>
    /// UpdateReferralInfo is passed to ReferralService.Update()
    /// </summary>
    public class UpdateReferralInfo
    {
        public UpdateReferralInfo() { }

        //Constructor to simplify searching by only referralid
        public UpdateReferralInfo(Referral referralObject)
        {
            query = new ReferralQuery()
            {
                primaryInfo = new ReferralPrimaryInfo()
                {
                    referralId = referralObject.id
                }
            };
            referral = referralObject;
        }
        public ReferralQuery query { get; set; }
        public Referral referral { get; set; }
    }
}

Controllers/ReferralsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RockApi.Services;
using RockApi;

namespace Rock.Controllers
{
    public class ReferralsController : Controller
    {
        public async Task<IActionResult> Index(string referralcode, string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
            var Service = new ReferralService();

            var QueryOptions = new QueryOptions();
            QueryOptions.Options.Add(new QueryOption("query", referralcode));

            var model = await Service.ListAsync(QueryOptions);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create(string referralCode, string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
            return View(new NewReferral() { referralCode = referralCode });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("referralCode,firstName,lastName,email")] NewReferral model, string returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Service = new ReferralService();
                    await Service.CreateAsync(model);
                }
                if (Url.IsLocalUrl(returnUrl)) return Redirect(returnUrl);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
                return View(model);
            }
        }
        public async Task<IActionResult> Edit(string id, string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
            var Service = new ReferralService();

            var QueryOptions = new QueryOptions();
            QueryOptions.Options.Add(new QueryOption("referralQuery", id));

            Referral model = await Service.GetAsync(QueryOptions);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Referral model, string returnUrl)
        {
            try
            {
                var Service = new ReferralService();
                await Service.UpdateAsync(new List<UpdateReferralInfo>() { new UpdateReferralInfo(model) });

                if (Url.IsLocalUrl(returnUrl)) return Redirect(returnUrl);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Delete(string id, string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
            return View();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string returnUrl)
        {
            try
            {
                var Service = new ReferralService();
                await Service.RemoveAsync(new List<RemoveReferralInfo> { new RemoveReferralInfo(id) });

                if (Url.IsLocalUrl(returnUrl)) return Redirect(returnUrl);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                if (Url.IsLocalUrl(returnUrl)) ViewData["returnUrl"] = returnUrl;
                return View();
            }
        }
    }
}

Views/Referrals/Create.cshtml
@model RockApi.NewReferral

@{
    ViewData["Title"] = "New Referral";
}
<div class="white-block">
    <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
    <h1>New Referral</h1>
    <hr />
    <form asp-action="Create">
        <input type="hidden" name="returnUrl" value="@ViewData["returnUrl"]" />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="referralCode" class="control-label"></label>
                    <input asp-for="referralCode" readonly class="form-control" />
                    <span asp-validation-for="referralCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="firstName" class="control-label"></label>
                    <input asp-for="firstName" class="form-control" />
                    <span asp-validation-for="firstName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="email" class="control-label"></label>
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lastName" class="control-label"></label>
                    <input asp-for="lastName" class="form-control" />
                    <span asp-validation-for="lastName" class="text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <div class="text-right">
            <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Referrals/Delete.cshtml
@{
    ViewBag.Title = "Delete Referral";
}

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="white-block">
            <br />
            <h5 class="text-center">Are you sure you want to delete this referral?</h5>
            <h6 class="text-center">
                This action is permanent
            </h6>
            <br />
            <hr />
            <div class="text-right">
                <form asp-action="Delete">
                    <input type="hidden" name="returnUrl" value="@ViewData["returnUrl"]" />
                    <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
                    <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Referrals/Edit.cshtml
@model RockApi.Referral

@{
    ViewData["Title"] = "Edit Referral";
}
<div class="white-block">
    <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
    <h1>Edit Referral</h1>
    <hr />
    <form asp-action="Edit">
        <input type="hidden" name="returnUrl" value="@ViewData["returnUrl"]" />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="id" class="control-label"></label>
                    <input asp-for="id" readonly class="form-control" />
                    <span asp-validation-for="id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="firstName" class="control-label"></label>
                    <input asp-for="firstName" class="form-control" />
                    <span asp-validation-for="firstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="email" class="control-label"></label>
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="preferredContact" class="control-label"></label>
                    <input asp-for="preferredContact" class="form-control" />
                    <span asp-validation-for="preferredContact" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="externalIdentifier" class="control-label"></label>
                    <input asp-for="externalIdentifier" class="form-control" />
                    <span asp-validation-for="externalIdentifier" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="note" class="control-label"></label>
                    <input asp-for="note" class="form-control" />
                    <span asp-validation-for="note" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="status" class="control-label"></label>
                    <input asp-for="status" class="form-control" />
                    <span asp-validation-for="status" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="lastName" class="control-label"></label>
                    <input asp-for="lastName" class="form-control" />
                    <span asp-validation-for="lastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="phoneNumber" class="control-label"></label>
                    <input asp-for="phoneNumber" class="form-control" />
                    <span asp-validation-for="phoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="companyName" class="control-label"></label>
                    <input asp-for="companyName" class="form-control" />
                    <span asp-validation-for="companyName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="amount" class="control-label"></label>
                    <input asp-for="amount" class="form-control" />
                    <span asp-validation-for="amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="publicNote" class="control-label"></label>
                    <input asp-for="publicNote" class="form-control" />
                    <span asp-validation-for="publicNote" class="text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <h4>Custom Info</h4>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="customOption1Name" class="control-label"></label>
                    <input asp-for="customOption1Name" class="form-control" />
                    <span asp-validation-for="customOption1Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customOption2Name" class="control-label"></label>
                    <input asp-for="customOption2Name" class="form-control" />
                    <span asp-validation-for="customOption2Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText1Name" class="control-label"></label>
                    <input asp-for="customText1Name" class="form-control" />
                    <span asp-validation-for="customText1Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText2Name" class="control-label"></label>
                    <input asp-for="customText2Name" class="form-control" />
                    <span asp-validation-for="customText2Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText3Name" class="control-label"></label>
                    <input asp-for="customText3Name" class="form-control" />
                    <span asp-validation-for="customText3Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="customOption1Value" class="control-label"></label>
                    <input asp-for="customOption1Value" class="form-control" />
                    <span asp-validation-for="customOption1Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customOption2Value" class="control-label"></label>
                    <input asp-for="customOption2Value" class="form-control" />
                    <span asp-validation-for="customOption2Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText1Value" class="control-label"></label>
                    <input asp-for="customText1Value" class="form-control" />
                    <span asp-validation-for="customText1Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText2Value" class="control-label"></label>
                    <input asp-for="customText2Value" class="form-control" />
                    <span asp-validation-for="customText2Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="customText3Value" class="control-label"></label>
                    <input asp-for="customText3Value" class="form-control" />
                    <span asp-validation-for="customText3Value" class="text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <div class="text-right">
            <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Referrals/Index.cshtml
@model List<Referral>
@{
    ViewData["Title"] = "Home Page";
}

<div class="white-block">
    <a class="btn btn-outline-primary" href="@ViewData["returnUrl"]">Back</a>
    <a class="btn btn-primary" asp-controller="Referrals" asp-action="Create" asp-route-referralcode="@Context.Request.Query["referralcode"]" asp-route-ReturnUrl="@Context.Request.GetEncodedPathAndQuery()">Add Referral</a>
    <h1 class="display-4">Referrals</h1>
    <span>Referrals: @Model.Count</span>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Status
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Program
                </th>
                <th>
                    Created
                </th>
                <th>
                    Qualified
                </th>
                <th>
                    Approved
                </th>
                <th class="text-right">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Referral r in Model)
            {
                <tr>
                    <td>
                        @r.displayName
                    </td>
                    <td>
                        @r.status
                    </td>
                    <td>
                        @r.amountFormatted
                    </td>
                    <td>
                        @r.programName
                    </td>
                    <td>
                        @DateTime.Parse(r.createDate).ToShortDateString()
                    </td>
                    <td>
                        @if (r.qualifiedDate != null)
                        {
                            @DateTime.Parse(r.qualifiedDate).ToShortDateString()
                        }
                    </td>
                    <td>
                        @if (r.approvedDate != null)
                        {
                            @DateTime.Parse(r.approvedDate).ToShortDateString()
                        }
                    </td>
                    <td class="text-right">
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@r.id" asp-route-ReturnUrl="@Context.Request.GetEncodedPathAndQuery()">Edit</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@r.id" asp-route-ReturnUrl="@Context.Request.GetEncodedPathAndQuery()">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>